# Server settings
server:
  port: 8080
  # HTTP请求和响应头的最大量，以字节为单位，默认值为4096字节,超过此长度的部分不予处理,一般8K。解决java.io.EOFException: null问题
  max-http-header-size: 8192
  use-forward-headers: true
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/plain,text/css,text/xml,text/javascript,application/json,application/javascript,application/xml,application/xml+rss,application/x-javascript,application/x-httpd-php,image/jpeg,image/gif,image/png
  tomcat:
    remote-ip-header: X-Forwarded-for
    protocol-header: X-Forwarded-Proto
    port-header: X-Forwarded-Port
    uri-encoding: UTF-8
    basedir: /var/tmp/website-app
# SPRING PROFILES
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dblog?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: MyZcPass1!
    initialSize: 20
    minIdle: 10
    maxActive: 100

  application:
    name: blog-web
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
    settings:
      template_update_delay: 0
      default_encoding: UTF-8
      classic_compatible: true
    # HTTP ENCODING
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  messages:
    encoding: UTF-8
  jmx:
    enabled: true
    default-domain: agentservice
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  # redis缓存服务配置
  session:
    store-type: redis
  # Redis数据库索引（默认为0）
  redis:
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        maxActive: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        maxWait: -1ms
        # 连接池中的最大空闲连接
        maxIdle: 8
        # 连接池中的最小空闲连接
        minIdle: 8
    # 连接超时时间（毫秒）
    timeout: 1000
    # 默认的数据过期时间，主要用于shiro权限管理
    expire: 2592000
  # 指定默认MimeMessage的编码，默认为: UTF-8
  mail:
    default-encoding: UTF-8
    # 指定SMTP server使用的协议，默认为: smtp
    protocol: smtp
    # 指定SMTP server host.
    host: smtp.sina.cn
    port: 465
    # 指定SMTP server的用户名.
    username: xxxx@sina.cn
    # 指定SMTP server登陆密码:
    password: xxxx
    # 指定是否在启动时测试邮件服务器连接，默认为false
    test-connection: false
    properties:
      mail.smtp.auth: true
      # 腾讯企业邮箱 下两个配置必须！！！
      mail.smtp.ssl.enable: true
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.port: 465
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 50000
      mail.smtp.timeout: 30000
      mail.smtp.writetimeout: 50000
  banner:
    charset: UTF-8
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
# MyBatis
mybatis:
  type-aliases-package: com.cchcz.blog.dao.beans
  mapper-locations: classpath:/mybatis/*.xml
# mapper
mapper:
  mappers:
  - com.cchcz.blog.dao.BaseMapper
  not-empty: false
  identity: MYSQL
# pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
####################################自定义配置##########################################
app:
  # 是否启用kaptcha验证码
  enableKaptcha: false
####################################自定义配置##########################################
#静态资源服务器地址
static.resource.url: